"use client";

export function LedgerReportButton() {
  return (
    <button
      type="button"
      className="mt-3 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-[var(--tcmf-primary)]"
      onClick={() => alert("Annual report PDF will be generated by the Django API when wired up.")}
    >
      Request PDF (mock)
    </button>
  );
}
